-- V003: forward migration from legacy JPA schema to purist-DDD target
--   ignore_user: add version (optimistic lock), migrate timestamps to TIMESTAMPTZ
--                (interpreting naive values as Asia/Seoul wall-clock per deploy TZ),
--                convert id to IDENTITY.
--   message_log: convert id to IDENTITY.
-- Rest of message_log alignment is deferred to stage 2/3 per spec.

-- ======================
-- ignore_user
-- ======================

-- 1) Optimistic lock column (rule AD-7)
ALTER TABLE ignore_user
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

-- 2) TIMESTAMPTZ conversion.
--    Existing naive timestamps were written by the old JPA BaseTimeEntity using
--    LocalDateTime.now(ZoneId.systemDefault()) on a container with TZ=Asia/Seoul
--    (deploy/docker-compose.yml), so they are KST wall-clock values.
--    'AT TIME ZONE Asia/Seoul' re-interprets them as KST and produces the
--    correct UTC instant.
--
--    The multi-action ALTER with USING clause is PostgreSQL-specific and not
--    supported by jOOQ DDLDatabase (H2 simulation). The jooq-ignore block contains
--    the PostgreSQL-specific USING form (executed by Flyway, skipped by jOOQ).
--    Single-column TYPE-only ALTERs outside the block provide jOOQ schema inference.
--[jooq ignore start]
ALTER TABLE ignore_user
    ALTER COLUMN created_at TYPE TIMESTAMPTZ
        USING created_at AT TIME ZONE 'Asia/Seoul',
    ALTER COLUMN created_at SET DEFAULT now(),
    ALTER COLUMN updated_at TYPE TIMESTAMPTZ
        USING updated_at AT TIME ZONE 'Asia/Seoul',
    ALTER COLUMN updated_at SET DEFAULT now();
--[jooq ignore stop]
ALTER TABLE ignore_user ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE ignore_user ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE ignore_user ALTER COLUMN updated_at TYPE TIMESTAMPTZ;
ALTER TABLE ignore_user ALTER COLUMN updated_at SET DEFAULT now();

-- 3) id IDENTITY conversion. BY DEFAULT accepts explicit values
--    (reconstitute path) and auto-generates when unspecified.
--    PostgreSQL-specific ALTER COLUMN ADD GENERATED is not supported by jOOQ
--    DDLDatabase; placed inside jooq-ignore (Flyway still executes it).
--    The identity flag is not referenced by adapter code; jOOQ's id field
--    type (BIGINT NOT NULL PRIMARY KEY from V001) is sufficient for compilation.
--[jooq ignore start]
ALTER TABLE ignore_user
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Advance the identity sequence past any existing row ids so auto-generation
-- never collides with legacy rows (setval with `true` makes the *next* call
-- to nextval return max+1).
SELECT setval(
    pg_get_serial_sequence('ignore_user', 'id'),
    COALESCE((SELECT MAX(id) FROM ignore_user), 1),
    true
);
--[jooq ignore stop]

-- ======================
-- message_log
-- ======================

-- 4) id IDENTITY conversion. Deployment blocker: every message conversion
--    calls MessageLogRecordAdapter.record(), which inserts without id.
--[jooq ignore start]
ALTER TABLE message_log
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(
    pg_get_serial_sequence('message_log', 'id'),
    COALESCE((SELECT MAX(id) FROM message_log), 1),
    true
);
--[jooq ignore stop]
